# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(953, 629)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(6, 2, 461, 641))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(466, -8, 491, 641))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(6, -8, 461, 131))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:/AI Project/LOGO.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 140, 411, 341))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("D:/AI Project/scanner.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(100, 520, 301, 51))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(600, 100, 221, 41))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:/AI Project/Face Login.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(520, 150, 391, 361))
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-width:2px 2px 2px 2px;\n"
"border-radius: 15px")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QPushButton(Form)
        self.label_8.setGeometry(QtCore.QRect(646, 563, 161, 31))
        self.label_8.setFont(QFont("Ariel",20))
        self.label_8.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: green;\n"
"background-color:black;\n"
"border-style:solid;\n"
"border-width:2px 2px 2px 2px;\n"
"border-radius: 15px")
        self.label_8.setText("Exit")
        self.label_8.setObjectName("label_8")


        self.label_9 = QtWidgets.QPushButton(Form)
        self.label_9.setGeometry(QtCore.QRect(646, 563, 161, 31))
        self.label_9.setFont(QFont("Ariel",20))
        self.label_9.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: green;\n"
"background-color:black;\n"
"border-style:solid;\n"
"border-width:2px 2px 2px 2px;\n"
"border-radius: 15px")
        self.label_9.setText("Next")
        self.label_9.setEnabled(False)
        self.label_9.hide()
        self.label_9.setObjectName("label_9")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:28pt; color:#ff0000;\">Face Scanning</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
